volumes:
  strapi-database-data:

networks:
  reverse-proxy:
    external: true
    name: ${REVERSE_PROXY_NETWORK}

services:
  strapi-database:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - strapi-database-data:/var/lib/postgresql/data
    networks:
      - default
      - reverse-proxy
    healthcheck:
      test: pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}

  strapi:
    build: .
    restart: always
    env_file: strapi/.env
    environment:
      DATABASE_HOST: strapi-database
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - strapi-database
    networks:
      - default
      - reverse-proxy
    healthcheck:
      test: wget -qO- http://127.0.0.1:1337
